[package]
name = "ds4-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ds4"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
ds4-core = { path = "../ds4-core" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
